# Generated by Django 4.0.4 on 2023-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.IntegerField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
