# Generated by Django 4.0.4 on 2023-04-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_login_table_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
