# Generated by Django 4.2 on 2023-04-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_metrostaion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStaionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('metrostaion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.metrostaion')),
            ],
        ),
    ]
