# Generated by Django 4.2 on 2023-04-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_metrostaioncontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metrostaion',
            new_name='Metrostation',
        ),
        migrations.RenameField(
            model_name='metrostaioncontact',
            old_name='metrostaion',
            new_name='metrostation',
        ),
    ]
