# Generated by Django 4.2 on 2023-04-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_metrostaion_metrostation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetroStaionContact',
            new_name='MetroStationContact',
        ),
    ]
