# Generated by Django 4.2 on 2023-04-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_rename_metrostaioncontact_metrostationcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrostation',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='metrostationcontact',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
