# Generated by Django 4.1.7 on 2023-04-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_metrostation_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=255, null=True)),
                ('space_type', models.CharField(max_length=255, null=True)),
                ('area_type', models.CharField(max_length=255, null=True)),
                ('area_side', models.CharField(max_length=255, null=True)),
                ('area_level', models.CharField(max_length=255, null=True)),
                ('area', models.BigIntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
                ('metrostation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.metrostation')),
            ],
        ),
    ]
