# Generated by Django 4.1.7 on 2023-04-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_spaces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spaces',
            new_name='Space',
        ),
    ]
