# Generated by Django 4.1.7 on 2023-05-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_space_master_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='master_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_spaces', to='firstapp.space'),
        ),
    ]
