# Generated by Django 4.1.7 on 2023-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_space_master_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='vacancy_status',
            field=models.IntegerField(null=True),
        ),
    ]
