# Generated by Django 4.2 on 2023-05-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_space_vacancy_status'),
        ('firstapp', '0017_alter_space_metrostation'),
    ]

    operations = [
    ]
