# Generated by Django 4.2 on 2023-05-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_merge_20230508_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.BigIntegerField(null=True)),
                ('customer_name', models.CharField(max_length=250, null=True)),
                ('business_type', models.CharField(max_length=250, null=True)),
                ('business_name', models.CharField(max_length=250, null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
            ],
        ),
        migrations.AlterField(
            model_name='space',
            name='area',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Customer_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=225, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('city', models.CharField(max_length=225, null=True)),
                ('district', models.CharField(max_length=225, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=225, null=True)),
                ('gst_no', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=225, null=True)),
                ('agreement_number', models.CharField(max_length=225, null=True)),
                ('agreement_date', models.DateField(null=True)),
                ('auction_number', models.CharField(max_length=225, null=True)),
                ('auction_date', models.DateField(null=True)),
                ('auction_notice_number', models.CharField(max_length=225, null=True)),
                ('auction_notice_date', models.DateField(null=True)),
                ('auction_notice_ref_number', models.CharField(max_length=225, null=True)),
                ('auction_notice_ref_date', models.DateField(null=True)),
                ('final_allotment_order_number', models.CharField(max_length=225, null=True)),
                ('final_allotment_ref_number', models.CharField(max_length=225, null=True)),
                ('rfp_number', models.CharField(max_length=225, null=True)),
                ('rfp_date', models.DateField(null=True)),
                ('rfp_ref_number', models.CharField(max_length=225, null=True)),
                ('rfp_ref_date', models.DateField(null=True)),
                ('loa_number', models.CharField(max_length=225, null=True)),
                ('loa_date', models.DateField(null=True)),
                ('invoice_start_date', models.DateField(null=True)),
                ('job_card_issue', models.CharField(max_length=225, null=True)),
                ('tenure_start_date', models.DateField(null=True)),
                ('tenure_end_date', models.DateField(null=True)),
                ('contract_period', models.IntegerField(null=True)),
                ('fitment_period', models.IntegerField(null=True)),
                ('lock_in_period', models.IntegerField(null=True)),
                ('bill_start_date', models.DateField(null=True)),
                ('rent_amount', models.BigIntegerField(null=True)),
                ('utility_charges', models.IntegerField(null=True)),
                ('cam_charges', models.IntegerField(null=True)),
                ('security_deposit', models.IntegerField(null=True)),
                ('hikes', models.IntegerField(null=True)),
                ('auth_sign', models.CharField(max_length=225, null=True)),
                ('desiginations', models.CharField(max_length=225, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer')),
                ('master_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.space')),
            ],
        ),
    ]
