# Generated by Django 4.1.7 on 2023-05-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_alter_space_area'),
        ('firstapp', '0019_customer_alter_space_area_customer_contact_contract'),
    ]

    operations = [
    ]
