# Generated by Django 4.2 on 2023-05-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_merge_20230513_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer_contact'),
        ),
        migrations.AlterField(
            model_name='customer_contact',
            name='gst_no',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
