# Generated by Django 4.2 on 2023-05-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_rename_customer_contract_customer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='final_allotment_ref_number',
        ),
        migrations.AddField(
            model_name='contract',
            name='final_allotment_order_date',
            field=models.DateField(null=True),
        ),
    ]
