# Generated by Django 4.1.7 on 2023-05-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_merge_20230515_0952'),
        ('firstapp', '0023_remove_contract_final_allotment_ref_number_and_more'),
    ]

    operations = [
    ]
