# Generated by Django 4.1.7 on 2023-05-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_merge_20230515_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='job_card_issue',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='security_deposit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='utility_charges',
            field=models.BigIntegerField(null=True),
        ),
    ]
