# Generated by Django 4.1.7 on 2023-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_contract_job_card_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
