# Generated by Django 4.1.7 on 2023-05-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=225, null=True)),
                ('city', models.CharField(max_length=225, null=True)),
                ('district', models.CharField(max_length=225, null=True)),
                ('state', models.CharField(max_length=225, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=225, null=True)),
                ('gst_no', models.CharField(max_length=225, null=True)),
                ('pan_no', models.CharField(max_length=225, null=True)),
                ('cin', models.CharField(max_length=225, null=True)),
                ('phno1', models.IntegerField(null=True)),
                ('phno2', models.IntegerField(null=True)),
                ('fax', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=225, null=True)),
                ('website', models.CharField(max_length=225, null=True)),
                ('state_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='sq_ft_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='pan_no',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='state_code',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(null=True)),
                ('invoice_issue_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('irn_no', models.CharField(max_length=225, null=True)),
                ('ack_no', models.BigIntegerField(null=True)),
                ('ack_date', models.DateField(null=True)),
                ('invoice_start_date', models.DateField(null=True)),
                ('invoice_end_date', models.DateField(null=True)),
                ('sac_code', models.BigIntegerField(null=True)),
                ('taxable_amount', models.BigIntegerField(null=True)),
                ('tax_percentage', models.IntegerField(null=True)),
                ('total_amount', models.BigIntegerField(null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.contract')),
                ('customer_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer_contact')),
                ('master_space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.space')),
            ],
        ),
    ]
