# Generated by Django 4.1.7 on 2023-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_company_details_contract_sq_ft_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_contact',
            name='state',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
