# Generated by Django 4.1.7 on 2023-05-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_customer_contact_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='job_card_issue',
        ),
    ]
