# Generated by Django 4.1.7 on 2023-05-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_remove_contract_job_card_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.company_details'),
        ),
    ]
