# Generated by Django 4.1.7 on 2023-05-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0030_invoices_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table'),
        ),
        migrations.AddField(
            model_name='company_details',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
