# Generated by Django 4.1.7 on 2023-05-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_company_details_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='fax',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='phno1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='phno2',
            field=models.BigIntegerField(null=True),
        ),
    ]
