# Generated by Django 4.1.7 on 2023-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_alter_company_details_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='master_space',
        ),
    ]
