# Generated by Django 4.1.7 on 2023-05-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_invoices_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='master_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.space'),
        ),
    ]
