# Generated by Django 4.1.7 on 2023-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_invoices_master_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
