# Generated by Django 4.1.7 on 2023-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_bank_alter_invoices_taxable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='maintanence',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
