# Generated by Django 4.1.7 on 2023-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_invoices_maintanence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='scgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
