# Generated by Django 4.1.7 on 2023-05-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_invoices_cgst_invoices_scgst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='scgst',
            new_name='sgst',
        ),
    ]
