# Generated by Django 4.1.7 on 2023-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_rename_scgst_invoices_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='fax',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='phno1',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='phno2',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
