# Generated by Django 4.1.7 on 2023-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_alter_company_details_fax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='tax_amount_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
