# Generated by Django 4.1.7 on 2023-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0042_invoices_tax_amount_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='acc_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='upi_id',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
