# Generated by Django 4.1.7 on 2023-05-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_bank_acc_no_bank_branch_name_bank_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table'),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
