# Generated by Django 4.1.7 on 2023-05-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_bank_created_by_bank_created_on_bank_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.bank'),
        ),
    ]
