# Generated by Django 4.1.7 on 2023-05-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0045_invoices_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
