# Generated by Django 4.1.7 on 2023-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0047_alter_company_details_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='signature',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
