# Generated by Django 4.1.7 on 2023-05-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0048_alter_company_details_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='signature',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
