# Generated by Django 4.1.7 on 2023-05-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0051_alter_company_details_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='signature',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/uploadedimages/'),
        ),
    ]
