# Generated by Django 4.2 on 2023-05-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0052_alter_company_details_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=225, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(max_length=225, null=True)),
                ('payment_status', models.IntegerField(null=True)),
                ('payment_history', models.CharField(max_length=225, null=True)),
                ('reciept_no', models.CharField(max_length=225, null=True)),
                ('notification', models.CharField(max_length=225, null=True)),
                ('notification_status', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer_contact')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.invoices')),
            ],
        ),
    ]
