# Generated by Django 4.2 on 2023-05-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0053_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payments_Data',
        ),
    ]
