# Generated by Django 4.2 on 2023-05-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_rename_payments_payments_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments_data',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
