# Generated by Django 4.1.7 on 2023-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0054_rename_signature_customer_grievance_complaint_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_grievance',
            name='complaint_pic',
            field=models.FileField(blank=True, default='get_default_file', null=True, upload_to='media/uploadedimages/'),
        ),
    ]
