# Generated by Django 4.1.7 on 2023-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0057_alter_customer_grievance_complaint_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_grievance',
            name='reply',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
