# Generated by Django 4.1.7 on 2023-05-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0055_rename_customer_id_payments_data_customer'),
        ('firstapp', '0059_metrostation_s_name'),
    ]

    operations = [
    ]
