# Generated by Django 4.1.7 on 2023-05-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0060_merge_20230525_1746'),
        ('firstapp', '0060_merge_20230525_1754'),
    ]

    operations = [
    ]
