# Generated by Django 4.1.7 on 2023-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0061_merge_20230527_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_table',
            name='phno',
            field=models.BigIntegerField(null=True),
        ),
    ]
