# Generated by Django 4.1.7 on 2023-05-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0062_login_table_email_login_table_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/uploadedimages/'),
        ),
    ]
