# Generated by Django 4.2 on 2023-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0063_login_table_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='login_table',
            name='phno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_table',
            name='notifications',
            field=models.ManyToManyField(to='firstapp.notification'),
        ),
    ]
