# Generated by Django 4.1.7 on 2023-06-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0067_alter_invoices_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='customer_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', related_query_name='invoice', to='firstapp.customer_contact'),
        ),
        migrations.AlterField(
            model_name='payments_data',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_data', related_query_name='payment', to='firstapp.customer_contact'),
        ),
    ]
