# Generated by Django 4.1.7 on 2023-06-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0068_alter_invoices_customer_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments_data',
            name='payment_status',
        ),
    ]
