# Generated by Django 4.2 on 2023-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0070_payments_data_master_space_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
