# Generated by Django 4.1.7 on 2023-06-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0071_login_table_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_contact',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_contact',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
