# Generated by Django 4.1.7 on 2023-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0073_rename_payment_history_payments_data_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invoice_no',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile_pic',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
