# Generated by Django 4.2 on 2023-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0074_notification_invoice_no_notification_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_type', models.CharField(max_length=225, null=True)),
                ('gp_value', models.CharField(max_length=225, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
