# Generated by Django 4.1.7 on 2023-06-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0075_general_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='profile_pic',
            field=models.FileField(blank=True, default='null', null=True, upload_to='media/uploadedimages/'),
        ),
    ]
