# Generated by Django 4.1.7 on 2023-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0077_alter_login_table_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='media/uploadedimages/'),
        ),
    ]
