# Generated by Django 4.2 on 2023-06-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0080_alter_login_table_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrostationcontact',
            name='address',
        ),
    ]
