# Generated by Django 4.1.7 on 2023-06-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0081_remove_metrostationcontact_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
