# Generated by Django 4.1.7 on 2023-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0082_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
        ),
    ]
