# Generated by Django 4.1.7 on 2023-06-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0083_test_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('age', models.BigIntegerField(null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=225, null=True)),
                ('location', models.CharField(max_length=225, null=True)),
                ('language', models.CharField(max_length=225, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_login',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='test_login',
            name='updated_on',
        ),
    ]
