# Generated by Django 4.1.7 on 2023-06-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0084_test_data_remove_test_login_updated_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_data',
        ),
        migrations.DeleteModel(
            name='test_login',
        ),
    ]
