# Generated by Django 4.1.7 on 2023-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0085_delete_test_data_delete_test_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
