# Generated by Django 4.1.7 on 2023-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0086_notification_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments_data',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
