# Generated by Django 4.1.7 on 2023-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0087_alter_payments_data_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(null=True),
        ),
    ]
