# Generated by Django 4.1.7 on 2023-07-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0088_contract_termination_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='media/uploadedimages/')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.contract')),
            ],
        ),
    ]
