# Generated by Django 4.1.7 on 2023-07-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0089_contractupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractupload',
            name='contracttype',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contractupload',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table'),
        ),
        migrations.AddField(
            model_name='contractupload',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
