# Generated by Django 4.1.7 on 2023-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0090_contractupload_contracttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractupload',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contractupload',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
