# Generated by Django 4.1.7 on 2023-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0091_contractupload_updated_by_contractupload_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='created_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='updated_on',
            field=models.DateField(null=True),
        ),
    ]
