# Generated by Django 4.1.7 on 2023-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0092_alter_invoices_created_on_alter_invoices_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
