# Generated by Django 4.1.7 on 2023-08-04 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0093_notification_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(null=True)),
                ('water', models.IntegerField(null=True)),
                ('powerpic', models.FileField(blank=True, default='', null=True, upload_to='media/uploadedimages/')),
                ('waterpic', models.FileField(blank=True, default='', null=True, upload_to='media/uploadedimages/')),
                ('created_on', models.DateField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.login_table')),
            ],
        ),
    ]
