# Generated by Django 4.1.7 on 2023-08-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0094_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='metrostation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.metrostationcontact'),
        ),
    ]
