# Generated by Django 4.1.7 on 2023-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0095_utility_metrostation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
