# Generated by Django 4.1.7 on 2023-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0096_utility_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='status',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='water',
            field=models.BigIntegerField(null=True),
        ),
    ]
