# Generated by Django 5.0.1 on 2024-02-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0098_intrestspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrestspace',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
