name: Django CI-CD Pipeline

on:
  push:
    branches:
      - my_pc  # Make sure this matches your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Navigate to the project folder
            cd ~/Cms-Kmrl
            
            # 2. Pull the latest changes from GitHub
            git pull origin main
            
            # 3. Clean up old Docker data to save space (Important!)
            docker system prune -f
            
            # 4. Rebuild the web container
            docker-compose build web
            
            # 5. Restart the services in detached mode
            docker-compose up -d