
from django.urls import path
from django.urls import re_path

from . import views
from .import secondviews
from .views import NotificationAPIView
from django.conf.urls.static import static
from django.conf import settings
from .import customerviews, utilityviews
from .customerviews import CNotificationAPIView


urlpatterns = [
    path('', views.signin, name='signin'),
    path('dashboardsuper', views.firstapp, name='firstapp'),
    path('logout',views.user_logout,name='user_logout'),
    path('user_create',views.adduser,name='adduser'),
    path('loginfunc',views.loginfunc,name='loginfunc'),
    path('metrostaion',views.Viewmetrostaions,name='Viewmetrostaions'),
    path('add_metrostation',views.Addmetrostaions,name='Addmetrostaions'),
    path('Update_metrostation/<int:pk>',views.Update_metrostation,name='Update_metrostation'),
    path('view_metrostation/<int:pk>',views.View_details_metrostation,name='View_details_metrostation'),
    path('deletemetrostaion/<int:pk>',views.deletemetrostaion,name='deletemetrostaion'),
    path('view_spaces',secondviews.Viewspaces,name='Viewspaces'),
    path('add_spaces',secondviews.Addspaces,name='Addspaces'),
    path('space_details/<int:pk>',secondviews.View_space_details, name='View_space_details'),
    path('update_space/<int:pk>',secondviews.Update_space,name='Update_space'),
    path('deletespace/<int:pk>',secondviews.deletespace,name='deletespace'),
    path('customers',secondviews.Viewcustomers,name="Viewcustomers"),
    path('approve_customer',secondviews.Approvecustomer,name="Approvecustomer"),
    path('approve_contracts',secondviews.Approvecontract,name="Approvecontract"),
    path('customer_registration_details/<int:pk>',secondviews.Approveregistration,name="Approveregistration"),
    path('customer_details/<int:pk>',secondviews.Customer_contracts,name="Customer_contracts"),
    path('customer_invoices',secondviews.Invoice,name="Invoice"),
    path('customer_payments',secondviews.Payments,name="Payments"),
    path('payment_report',secondviews.Payment_report,name="Payment_report"),
    path('manage_users',secondviews.Manage_users,name="Manage_users"),
    path('profile_settings',secondviews.Profile_settings,name="Profile_settings"),
    path('notifications',secondviews.Notfication_settings,name="Notification_settings"),
    path('change_password',secondviews.Change_password,name="Change_password"),
    path('delete_account',secondviews.Delete_account,name="Delete_account"),
    path('bank_details',secondviews.Bank_settings,name="Bank_settings"),
    path('profile',secondviews.Profile,name="Profile"),
    path('space_details_contract/<int:pk>',views.space_details_contract,name='space_details_contract'),
    path('approved/<int:pk>',secondviews.Approved_customer,name="Approved_customer"),
    path('rejected/<int:pk>',secondviews.Rejected_customer,name="Rejected_customer"),
    path('approves/<int:pk>',secondviews.Approved_contract,name="Approved_contract"),
    path('rejects/<int:pk>',secondviews.Rejected_contract,name="Rejected_contract"),
    path('deletecustomer/<int:pk>',secondviews.deletecustomer,name='deletecustomer'),
    path('add_contract',secondviews.Add_contracts,name="Add_contracts"),
    path('view_contracts',secondviews.View_contract,name="View_contract"),
    path('deletecontract/<int:pk>',secondviews.deletecontract,name='deletecontract'),
    path('update_contracts/<int:pk>',secondviews.Update_contracts,name='Update_contracts'),
    path('contract_details/<int:pk>',secondviews.View_details_contract,name='View_details_contract'),
    path('add_invoice',secondviews.Addinvoice,name='Addinvoice'),
    path('add_company_details',secondviews.Add_company_details,name='Add_company_details'),
    path('view_company_details',secondviews.View_company_details,name='View_company_details'),
    path('edit_company_details/<int:pk>',secondviews.Update_company_details,name='Update_company_details'),
    path('Customer_detais_contract/<int:pk>',views.Customer_detais_contract,name='Customer_detais_contract'),  
    path('select_masterspaces/<int:pk>',secondviews.select_masterspaces,name='select_masterspaces'),
    path('invoice_details/<int:pk>',secondviews.View_invoice,name='View_invoice'),
    path('Customer_details_invoice/<int:pk>',views.Customer_details_invoice,name='Customer_details_invoice'), 
    path('space_details_customer/<int:pk>',views.space_details_customer,name="space_details_customer"),
    path('deleteinvoice/<int:pk>',secondviews.deleteinvoice,name='deleteinvoice'),
    path('deletebank/<int:pk>',secondviews.deletebank,name='deletebank'),
    path('add_bank',secondviews.Add_bank_details,name='Add_bank_details'),
    path('edit_bank/<int:pk>',secondviews.Update_bank_details,name='Update_bank_details'),
    path('view_bank/<int:pk>',secondviews.view_bank,name='view_bank'),
    path('edit_invoice/<int:pk>',secondviews.Update_invoice,name='Update_invoice'),
    path('Update_user/<int:pk>',views.Update_user,name='Update_user'),
    path('deleteuser/<int:pk>',views.deleteuser,name='deleteuser'),
    path('grievances',secondviews.View_grievances,name='View_grievances'),
    path('add_grievance',secondviews.Add_grievance,name='Add_grievance'),
    path('deletegrievance/<int:pk>',secondviews.deletegrievance,name='deletegrievance'),
    path('edit_grievance/<int:pk>',secondviews.Update_grievance,name='Update_grievance'),
    path('view_grievance/<int:pk>',secondviews.view_grievance,name='view_grievance'),
    path('grievance_details/<int:pk>',secondviews.View_grievance_details,name='View_grievance_details'),
    path('customer_grievances',secondviews.View_customer_grievances,name='View_customer_grievances'),
    path('deletecustomergrievance/<int:pk>',secondviews.deletecustomergrievance,name='deletecustomergrievance'),
    path('customer_grievance_form/<int:pk>',secondviews.Customer_grievance_form,name='Customer_grievance_form'),
    path('reply/<int:pk>',secondviews.ReplyMessage,name='ReplyMessage'),
    path('space_details_payments/<int:pk>',views.space_details_payments,name='space_details_payments'),
    path('Customer_details_payment/<int:pk>',views. Customer_details_payment,name='Customer_details_payment'),
    path('api/notifications/', NotificationAPIView.as_view(), name='notifications-api'),
    path('api/adminprofile/', secondviews.view_adminprofile, name='view_adminprofile'),
    path('send_invoice/<int:pk>',secondviews.send_invoice,name='send_invoice'),
    path('activatespace/<int:pk>',secondviews.activatespace,name='activatespace'),
    path('activatecustomer/<int:pk>',secondviews.activatecustomer,name='activatecustomer'),
    path('send_all_invoice',secondviews.send_all_invoice,name='send_all_invoice'),
    path('Create_all_invoices',secondviews.Create_all_invoices,name='Create_all_invoices'),
    path('progress/<int:pk>',secondviews.progress,name='progress'),
    path('prospective/<int:pk>',secondviews.prospective,name='prospective'),
    path('general_parameter',secondviews.general_parameter,name='general_parameter'),
    path('general_parameter/post',secondviews.Gpmodel_view.as_view(),name='gp_view'),
    path('general_parameter/get/<int:pk>',secondviews.get_gptype,name='get_gptype'),
    path('general_parameter/edit/<int:pk>',secondviews.update_gp,name='update_gp'),
    path('inactive_gp/<int:pk>',secondviews.inactive_gp,name='inactive_gp'),
    path('active_gp/<int:pk>',secondviews.active_gp,name='active_gp'),
    path('activateuser/<int:pk>',secondviews.activateuser,name='activateuser'),
    path('admin-email', secondviews.admin_mail, name='admin_mail'),
    path('edit_customer/<int:pk>',secondviews.Add_customer_details,name='Add_customer_details'),
    path('IntrestSpaceView',views.IntrestSpaceView,name='IntrestSpaceView'),

#customer url
    path('dashboard',customerviews.customer_dasboard,name='customer_dasboard'),
    path('register',customerviews.register,name='register'),
    path('invoices',customerviews.Customer_invoice,name='Customer_invoice'),
    path('invoice_detail/<int:pk>',customerviews.Customer_invoice_details,name='Customer_invoice_details'),
    path('profile_info',customerviews.Customer_profile,name='Customer_profile'),
    path('edit_profile',customerviews.Customer_edit_profile,name='Customer_edit_profile'),
    path('api/view_profile/', customerviews.view_profile, name='view_profile'),
    path('changepassword', customerviews.Customer_change_password, name='Customer_change_password'),
    path('invoice_payment/success',customerviews.invoice_payment,name='invoice_payment'),
    path('payments',customerviews.customer_payments,name='customer_payments'),
    path('contracts',customerviews.customer_contract,name='customer_contract'),
    path('contract-details/<int:pk>',customerviews.customer_contract_details,name='customer_contract_details'),
    path('api/cnotifications/', CNotificationAPIView.as_view(), name='cnotifications-api'),
    path('send-email', customerviews.send_email, name='send_email'),
    path('due_notification', customerviews.due_notification, name='due_notification'),
    path('vacant_spaces',customerviews.vacantSpaces,name='vacantSpaces'),
    path('View_Vacant_space_details/<int:pk>',customerviews.View_Vacant_space_details,name='View_Vacant_space_details'),
    path('api/intestSpace',customerviews.intestSpace,name='intestSpace'),

#utility url
    path('power',utilityviews.view_utility,name='view_utility'),
    path('add_power',utilityviews.Add_power,name='Add_power'),
    path('water',utilityviews.view_water,name='view_water'),
    path('add_water',utilityviews.Add_water,name='Add_water'),
    path('deletewater/<int:pk>',utilityviews.deletewater,name='deletewater'),
    path('deletepower/<int:pk>',utilityviews.deletepower,name='deletepower'),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
